server:
  port: 8085

userServer:
  connectTimeout: 70000
  readTimeout: 70000
  maxRetries: 1 # if call fail,it will try to recall times
  endpoint:   # if in cloud env,should be set empty,if not,should be set a fixed address

thrift:
  client:
    max:
      poolobject: 100 # pool object num,default is ten