server:
  port: 8085

userClient:
  connectTimeout: 3000
  readTimeout: 3000
  maxRetries: 1 # if call fail,it will try to recall times
  endpoint:   # if in cloud env,should be set empty,if not,should be set a fixed address

thrift:
  client:
    max:
      poolobject: 10 # pool object num,default is ten